[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "munch-group"]
name = "instructing-machines"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
nodejs = ">=26.5.0,<26.6"
nbconvert = ">=7.17.1,<8"
quarto = ">=1.9.38,<2"
ipython = ">=9.15.0,<10"
ipykernel = ">=7.3.0,<8"
nbdime = ">=4.0.4,<5"
seaborn = ">=0.13.2,<0.14"
steps-widget = ">=0.2.3,<0.3"
script-widget = ">=1.0.1,<2"
puzzle-widget = ">=0.1.14,<0.2"
turtle-widget = ">=0.1.24,<0.2"
codelens-widget = ">=0.1.40,<0.2"
snippet-cast = ">=0.1.35,<0.2"
