
# Learning learning

Studying is all about learning and understanding stuff. When the Danish state covers your tuition and supports your living as a student, it is because learning and understanding lets you contribute value back to society once you get a job. Because that value often takes the form of something you *produce*, it is easy to end up thinking that studying is some kind of “production training”. However, landing your first job, you will most likely find that the “production skills” you acquired  in college do not overlap a whole lot with the skills you need in your job. All jobs are different, 

If you are reading this (and you are), you must be studying already. Hopefully interest or curiosity were among the reasons you picked the program you are on and it is worth spending some time to think about what that interest is and how it made you decide to spend five years pursuing it.

What makes us want to learn something? 

How do you learn? How do you know what I tell you is true? How do you know what the AI tells you is true?

Learning a topic is to find internal consistency among facts that lets you explain the information you have and deduce/predict the information you do not yet have.

Internally consistency is the abstract patterns, general rules, or reasoning that lets you *explain* something.

You monitor your learning process by continually evaluating the internal consistency of you knowledge by testing its predictions.

That is all you can do, and all that is relevant. It may all only a weak proxy for the true reality, but one that suffice for prediction.